---
# AMQ Instalation Source

binary:
  folder: '/tmp/'

# AMQ Version and Patch
amq:
  version: '7.2'
  patch: '2'

# Patch AMQ Version and Patch
amq_patch:
  version: '7.2'
  patch: '2'

# AMQ shared storage
amq_broker_data_dir: /var/amq/data

# AMQ logs 
amq_broker_log_dir: /var/amq/log

# OS User to install/execute AMQ
user:
  name: "{{ vault_os_amq.user }}"
  group: "{{ vault_os_amq.group }}"
  shell: '/bin/bash'
  homedir: 'True'

# OS Global Variables

# AMQ Home
amq_home: '/var/amq'
amq_core_dir: '{{ amq_home }}/amq_core'
amq_broker_dir: '{{ amq_home }}/instance'


#####

# Fundamentals
# usually this is set at the playbook level
amq_broker_name: broker

# Primary admin user and role with which the broker is created
amq_broker_admin:
  name: "{{ vault_amq_broker_admin.user }}"
  password: "{{ vault_amq_broker_admin.password }}"
  role: admins

# Additional AMQ users
amq_broker_users: 
  - name: "{{ vault_amq_monitoring.user }}"
    password: "{{ vault_amq_monitoring.password }}"
    role: view


##### AMQ configuration

# Messaging roles
# each item of .permissions can be one of:
#   - createNonDurableQueue
#   - deleteNonDurableQueue
#   - createDurableQueue
#   - deleteDurableQueue
#   - createAddress
#   - deleteAddress
#   - consume
#   - browse
#   - send
#   - manage
amq_broker_roles_permissions: 
  - name: admins
    admin: True
    permissions:
      - browse
      - consume
      - send
  - name: view
    admin: False
    permissions:
      - browse
      - consume
      - send

# Clustering
amq_broker_clustered: True
amq_broker_cluster_user: "{{ vault_amq_broker_cluster.user }}"
amq_broker_cluster_password: "{{ vault_amq_broker_cluster.password }}"
amq_broker_cluster_maxhops: 0
amq_broker_cluster_load_balancing_policy: ON_DEMAND
amq_broker_cluster_discovery: False
amq_broker_slave: False
amq_broker_replicated: False

## Shared Storage
amq_broker_shared_storage: True

## Broker Memory Limit
global_max_size_on: True
global_max_size: 2GB

# Journal compact
journal_compact_on: True
journal_compact_min_files: 10
journal_compact_percentage: 30

# Console access
amq_custom_console_access: True

