---
amq_broker_name: broker-master
amq_console_port: 8161

# Port assignments
amq_broker_ports:
  artemis:
    port: 61616
  amqp:
    port: 5672
  stomp:
    port: 61613
  hornetq:
    port: 5445
  mqtt:
    port: 1833
    
delete_data_content: false
delete_log_content: True